# kitti_object_vis_re  

## 0318:  
新建了一个conda环境，使用python3.7试图复现，但是卡在了一个问题上，log文件在0318.log中  
